# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b62a7c7687c1c7e69cd42c42e80383c6d7ba7c144377e872e88cb4442c67f5a7aa3a03731afc415bb4fe0dd9f8007530b4847b52497e6d0e73ca99209d159ab

test:
  secret_key_base: 25e15fb9e76d64b9cbfabcd13ba3ec46cda8a95aed534a0d4d7bd3ebc592bb20e2dbf113230b786cae2330686fb0fa03ae84381e101d03b954b6bc57a2002ea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 25e15fb9e76d64b9cbfabcd13ba3ec46cda8a95aed534a0d4d7bd3ebc592bb20e2dbf113230b786cae2330686fb0fa03ae84381e101d03b954b6bc57a2002ea1  #<%= ENV["SECRET_KEY_BASE"] %>
